# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.User')),
            ],
        ),
    ]
